POST http://localhost:3001/api/posts
Content-Type: application/json

{
  "title": "Title example",
  "body": "lorem ipsum dolor sit am"
}

###

POST http://localhost:3001/api/posts
Content-Type: application/json

{
  "title": "Title example"
}

###

POST https://mysterious-gorge-57369.herokuapp.com/api/posts
Content-Type: application/json

{
  "title": "Title example Gonza333",
  "body": "lorem ipsum dolor sit am"
}
